/* dm-ref EDIT: file added */
// Extra search words per page, used by the site search bar and the MCP index.
// Mostly the names other langs give our operators, plus common words for shortened proc names.
export const searchKeywords: Record<string, string[]> = {
  "operator/ampamp": ["logical and", "boolean and"],
  "operator/vertvert": ["logical or", "boolean or", "null coalescing"],
  "operator/exclaim": ["logical not", "boolean not", "negation"],
  "operator/ampampequals": ["logical and assignment"],
  "operator/vertvertequals": ["logical or assignment", "null coalescing assignment"],
  "operator/amp/index": ["bitwise and", "bitflag", "bit flag", "intersection"],
  "operator/vert": ["bitwise or", "bitflag", "bit flag", "union"],
  "operator/caret": ["bitwise xor", "exclusive or", "bitflag", "bit flag"],
  "operator/tilde": ["bitwise not", "complement"],
  "operator/ampequals": ["bitwise and assignment"],
  "operator/vertequals": ["bitwise or assignment"],
  "operator/caretequals": ["bitwise xor assignment"],
  "operator/lessless/shift": ["left shift", "bit shift"],
  "operator/greatergreater/shift": ["right shift", "bit shift"],
  "operator/lesslessequals": ["left shift assignment"],
  "operator/greatergreaterequals": ["right shift assignment"],
  "operator/plus": ["addition", "concatenation"],
  "operator/minus": ["negation"],
  "operator/asterisk/index": ["multiplication"],
  "operator/slash": ["division"],
  "operator/modulo": ["remainder", "modulus", "mod"],
  "operator/modulomodulo": ["modulus", "mod", "fmod"],
  "operator/asteriskasterisk": ["exponent", "exponentiation", "pow"],
  "operator/plusplus": ["increment"],
  "operator/minusminus": ["decrement"],
  "operator/equals": ["assignment"],
  "operator/equalsequals": ["equality", "equal to"],
  "operator/exclaimequals": ["inequality", "not equal"],
  "operator/lessgreater": ["inequality", "not equal"],
  "operator/tildeequals": ["equivalence", "deep equality"],
  "operator/tildeexclaim": ["not equivalent"],
  "operator/less": ["less than"],
  "operator/lessequals": ["less than or equal"],
  "operator/greater": ["greater than"],
  "operator/greaterequals": ["greater than or equal"],
  "operator/lessequalsgreater": ["spaceship", "three way comparison"],
  "operator/query": ["ternary", "conditional operator"],
  "operator/querydot": ["null conditional", "safe navigation", "optional chaining"],
  "operator/querycolon": ["null conditional", "safe navigation", "optional chaining"],
  "operator/queryleftsquarerightsquare": [
    "null conditional",
    "safe navigation",
    "optional chaining",
  ],
  "operator/dot": ["member access"],
  "operator/coloncolon": ["scope resolution"],
  "operator/leftsquarerightsquare": ["index", "subscript"],
  "operator/leftparenrightparen": ["grouping", "precedence"],
  "operator/in": ["contains", "membership"],
  "operator/amp/pointer": ["address of", "reference"],

  "DM/text/index": ["string", "string interpolation"],
  "proc/num2text": ["number to string", "convert"],
  "proc/text2num": ["string to number", "parse number", "parse int", "convert"],
  "proc/text2path": ["string to typepath", "string to path", "convert"],
  "proc/copytext": ["substring", "substr", "slice string"],
  "proc/findtext": ["find text", "substring", "index of"],
  "proc/replacetext": ["replace string", "replace all"],
  "proc/jointext": ["join string"],
  "proc/lowertext": ["lower case string"],
  "proc/uppertext": ["uppercase", "upper case string"],
  "proc/length": ["len", "size", "count"],
  "proc/json_decode": ["parse json"],
  "proc/rand": ["random", "random number"],
  "proc/prob": ["random chance"],
  "proc/pick": ["random element", "random choice"],
  "proc/del": ["delete"],
  "proc/spawn": ["async", "thread", "non blocking", "nonblocking"],
  "proc/istype": ["type check", "typecheck", "instanceof"],
  "proc/dotdot": ["super"],
  "proc/for/list": ["foreach", "for each"],
  "var/global": ["static", "global variable"],
}
